#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

script=$(readlink "$initscript")
NAME="$(basename ${script:-$initscript})"
PROG="/usr/bin/magitrickled"

start_service() {
        config_load "$NAME"

        local enabled user
        config_get_bool enabled "main" "enabled" "0"
        [ "$enabled" -eq "1" ] || return 0

        config_get user "main" "user" "root"

        procd_open_instance "$NAME.main"
        procd_set_param command "$PROG"

        procd_set_param stdout 1
        procd_set_param stderr 1
        procd_set_param respawn

        procd_close_instance
}
